// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltimateWeb.Data;

namespace UltimateWeb.Migrations
{
    [DbContext(typeof(UltimateWebContext))]
    partial class UltimateWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UltimateWeb.Models.Aluno", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TreinadorCPF")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.HasKey("Cpf");

                    b.HasIndex("TreinadorCPF");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("UltimateWeb.Models.Treinador", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CPF");

                    b.ToTable("Treinador");
                });

            modelBuilder.Entity("UltimateWeb.Models.Usuario", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Permissoes")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Username");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("UltimateWeb.Models.Aluno", b =>
                {
                    b.HasOne("UltimateWeb.Models.Treinador", null)
                        .WithMany("Alunos")
                        .HasForeignKey("TreinadorCPF");
                });
#pragma warning restore 612, 618
        }
    }
}
